In [146]:
!ls

sample_data


In [147]:
import pandas as pd

In [148]:
from sklearn.datasets import load_iris

In [149]:
data = load_iris()

In [150]:
df = pd.DataFrame(data.data, columns = data.feature_names)
df['encoded_target'] = data.target

In [151]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

# **Lidando com Dados Nulos e Corrompidos**

In [152]:
df.iloc[0,0] = None
df.iloc[0,1] = None
df.iloc[0,2] = None
df.iloc[1,0] = None
df.iloc[4,3] = None
df.iloc[3,3] = -999999999999999999999999
df.iloc[149,2] = "batatinhafrita123"

/tmp/ipython-input-2063510329.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'batatinhafrita123' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[149,2] = "batatinhafrita123"


In [153]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  NaN               NaN                NaN      2.000000e-01   
1                  NaN               3.0                1.4      2.000000e-01   
2                  4.7               3.2                1.3      2.000000e-01   
3                  4.6               3.1                1.5     -1.000000e+24   
4                  5.0               3.6                1.4               NaN   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2      2.300000e+00   
146                6.3               2.5                5.0      1.900000e+00   
147                6.5               3.0                5.2      2.000000e+00   
148                6.2               3.4                5.4      2.300000e+00   
149                5.9               3.0  batatinhafrita123      1.800000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

# **Identificando os valores nulos no DF**
   Marca como True pontos de dados faltantes

In [154]:
df.isna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 True              True               True             False   
1                 True             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False              True   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False              False             False   

     encoded_target  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
145           False  
146           False  
147           False  
148           False  
149           False  

[150 rows x 5 columns]

Abaixo verificamos as que as linhas 0, 1 e 4 são as linhas com registros faltantes :

In [155]:
df[df.isna().any(axis=1)]

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                NaN               NaN               NaN               0.2   
1                NaN               3.0               1.4               0.2   
4                5.0               3.6               1.4               NaN   

   encoded_target  
0               0  
1               0  
4               0

# **Apagando as linhas faltantes com dropna:**

In [156]:
df_sem_faltantes = df.dropna()
df_sem_faltantes

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
2                  4.7               3.2                1.3      2.000000e-01   
3                  4.6               3.1                1.5     -1.000000e+24   
5                  5.4               3.9                1.7      4.000000e-01   
6                  4.6               3.4                1.4      3.000000e-01   
7                  5.0               3.4                1.5      2.000000e-01   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2      2.300000e+00   
146                6.3               2.5                5.0      1.900000e+00   
147                6.5               3.0                5.2      2.000000e+00   
148                6.2               3.4                5.4      2.300000e+00   
149                5.9               3.0  batatinhafrita123      1.800000e+00   

     encoded_target  
2                 0  
3                 0  
5                 0  
6                 0  
7                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[147 rows x 5 columns]

# **Alternativa seria fazer substituição**


1.   **pela média da coluna com mean()** - Este seria o meio mais comum de tratamento mas implica na interferência nos dados, tome cuidado se os seus dados tem escala negativa e positiva
2.   **por zero com** - substituir por zero pode acrescer a média podendo prejudicar sua distribuição.
3.   **por valor impossível** - cria outlayers mas identifica os dados com problema.


# **substitui pela média da coluna**
#### df_media = df.fillna(df.mean())

# **substitui por zero**
#### df_zero = df.fillna(0)

# **substitui por valor impossível**
#### df_impossiveis = df.fillna(-999)



# **Vamos continuar a partir do df_zero**

In [157]:
df_zero = df.fillna(0) # substitui por zero
df = df_zero
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  0.0               0.0                  0      2.000000e-01   
1                  0.0               3.0                1.4      2.000000e-01   
2                  4.7               3.2                1.3      2.000000e-01   
3                  4.6               3.1                1.5     -1.000000e+24   
4                  5.0               3.6                1.4      0.000000e+00   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2      2.300000e+00   
146                6.3               2.5                5.0      1.900000e+00   
147                6.5               3.0                5.2      2.000000e+00   
148                6.2               3.4                5.4      2.300000e+00   
149                5.9               3.0  batatinhafrita123      1.800000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

# **Dados corrompidos**


*  Verificamos por df.info() que a coluna   **petal length (cm)**  é    **object** .

Se verifica que era esperado um valor de inteiro ou float na coluna pois se trata de dado em cm.

A coluna foi classificada como object porque inserimos artificialmente "batatinhafrita123" na linha 149 coluna "petal length (cm)".

Desta forma simulamos um registro corrompido para exemplificar como encontramos estes registros corrompidos.




In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    object 
 3   petal width (cm)   150 non-null    float64
 4   encoded_target     150 non-null    int64  
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB


# **Identificando os dados corrompidos**

In [159]:
df['petal length (cm)'].unique()

array([0, 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9, 4.7, 4.5, 4.9, 4.0,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5.0, 3.8, 3.7,
       5.1, 3.0, 6.0, 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2, 'batatinhafrita123'], dtype=object)

# **Dropando registros corrompidos**

In [160]:
df = df[df['petal length (cm)'] != 'batatinhafrita123'].reset_index(drop=True)
df

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                  0.0               0.0                 0      2.000000e-01   
1                  0.0               3.0               1.4      2.000000e-01   
2                  4.7               3.2               1.3      2.000000e-01   
3                  4.6               3.1               1.5     -1.000000e+24   
4                  5.0               3.6               1.4      0.000000e+00   
..                 ...               ...               ...               ...   
144                6.7               3.3               5.7      2.500000e+00   
145                6.7               3.0               5.2      2.300000e+00   
146                6.3               2.5               5.0      1.900000e+00   
147                6.5               3.0               5.2      2.000000e+00   
148                6.2               3.4               5.4      2.300000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
144               2  
145               2  
146               2  
147               2  
148               2  

[149 rows x 5 columns]

In [161]:
df['petal length (cm)'].unique()

array([0, 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9, 4.7, 4.5, 4.9, 4.0,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5.0, 3.8, 3.7,
       5.1, 3.0, 6.0, 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2], dtype=object)

# **Verificando pontos fora da curva**

Abaixo podemos ver -1.0e+24 foi o número -999999999999999999999999 que inserimos no início propositadamente.

In [162]:
df['petal width (cm)'].unique()

array([ 2.0e-01, -1.0e+24,  0.0e+00,  4.0e-01,  3.0e-01,  1.0e-01,
        5.0e-01,  6.0e-01,  1.4e+00,  1.5e+00,  1.3e+00,  1.6e+00,
        1.0e+00,  1.1e+00,  1.8e+00,  1.2e+00,  1.7e+00,  2.5e+00,
        1.9e+00,  2.1e+00,  2.2e+00,  2.0e+00,  2.4e+00,  2.3e+00])

# **Removendo pontos fora da curva**

In [163]:
df = df[df['petal width (cm)']!= -1.0e+24]
df['petal width (cm)'].unique()

array([0.2, 0. , 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1,
       1.8, 1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

# **adicionando a coluna artificial**

In [164]:
import numpy as np

df['artificial'] = np.random.uniform(100,1000,df.shape[0]).round(2)

/tmp/ipython-input-1110814284.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['artificial'] = np.random.uniform(100,1000,df.shape[0]).round(2)


In [165]:
df

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                  0.0               0.0                 0               0.2   
1                  0.0               3.0               1.4               0.2   
2                  4.7               3.2               1.3               0.2   
4                  5.0               3.6               1.4               0.0   
5                  5.4               3.9               1.7               0.4   
..                 ...               ...               ...               ...   
144                6.7               3.3               5.7               2.5   
145                6.7               3.0               5.2               2.3   
146                6.3               2.5               5.0               1.9   
147                6.5               3.0               5.2               2.0   
148                6.2               3.4               5.4               2.3   

     encoded_target  artificial  
0                 0      595.62  
1                 0      999.05  
2                 0      613.12  
4                 0      474.76  
5                 0      706.19  
..              ...         ...  
144               2      832.49  
145               2      167.70  
146               2      554.88  
147               2      849.15  
148               2      833.29  

[148 rows x 6 columns]

# **Regularização de Dados**



*   Vamos fazer a regularização MinMaxScaler para que todos os valores mantenham suas proporções entre 0 e 1 o que facilita o treinamento de máquina.




In [166]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

print(scaler.fit(df))

novo_df = scaler.transform(df)


MinMaxScaler()


In [167]:
novo_df = pd.DataFrame(novo_df, columns = df.columns).round(2)
novo_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 0.00              0.00               0.00              0.08   
1                 0.00              0.68               0.20              0.08   
2                 0.59              0.73               0.19              0.08   
3                 0.63              0.82               0.20              0.00   
4                 0.68              0.89               0.25              0.16   
..                 ...               ...                ...               ...   
143               0.85              0.75               0.83              1.00   
144               0.85              0.68               0.75              0.92   
145               0.80              0.57               0.72              0.76   
146               0.82              0.68               0.75              0.80   
147               0.78              0.77               0.78              0.92   

     encoded_target  artificial  
0               0.0        0.54  
1               0.0        1.00  
2               0.0        0.56  
3               0.0        0.41  
4               0.0        0.67  
..              ...         ...  
143             1.0        0.81  
144             1.0        0.06  
145             1.0        0.50  
146             1.0        0.83  
147             1.0        0.81  

[148 rows x 6 columns]

In [168]:
novo_df['encoded_target'].unique()

array([0. , 0.5, 1. ])

In [169]:
novo_df['petal width (cm)'].unique()

array([0.08, 0.  , 0.16, 0.12, 0.04, 0.2 , 0.24, 0.56, 0.6 , 0.52, 0.64,
       0.4 , 0.44, 0.72, 0.48, 0.68, 1.  , 0.76, 0.84, 0.88, 0.8 , 0.96,
       0.92])